"""
Loader for Loghub-style alert data (AIOps2020 challenge dataset or any Loghub
log corpus normalized to the same shape).

The real AIOps2020 dataset ships as multi-gigabyte trace/metric/log bundles
with its own schema per data source, which is impractical to bundle in a repo
and risky to parse live on a conference stage. So this loader targets a
simple, documented normalized CSV schema (timestamp, component, level,
message) -- see README.md "Bringing your own dataset".

The bundled `sample_loghub.csv` is not a fabricated fixture: it's a real
~675-alert slice (2020-05-27, 18:00-21:00 UTC) of threshold-rule alerts
generated by app/data/aiops_loader.py against an actual local copy of the
AIOps2020 dataset -- `component` is the real `cmdb_id` host identifier and
`message` embeds the real metric name and value. It's checked in so the
real-data code path is exercised and testable even without the full dataset
present.

If NUCLEUS_AIOPS_DATASET_ROOT points at a real local copy of the dataset,
app/store.py regenerates alerts live via aiops_loader instead of using this
bundled slice. Any parsing failure here raises `DatasetLoadError`; callers
catch this and fall back to the synthetic generator, because the live demo
must never break on a bad file.
"""
import itertools
from pathlib import Path

import pandas as pd

from app.data.service_graph import ALL_SERVICES

_HERE = Path(__file__).parent
BUNDLED_SAMPLE = _HERE / "sample_loghub.csv"
REAL_DATASET_PATH = _HERE / "raw" / "dataset.csv"

REQUIRED_COLUMNS = {"timestamp", "component", "level", "message"}

_LEVEL_MAP = {
    "critical": "critical", "crit": "critical", "fatal": "critical", "error": "critical",
    "warn": "warning", "warning": "warning",
    "info": "info", "notice": "info", "debug": "info",
}
_SEVERITY_RANK = {"critical": 3, "warning": 2, "info": 1}


class DatasetLoadError(Exception):
    """Raised when a dataset file is missing, malformed, or empty."""


def _normalize_level(raw_level: str) -> str:
    return _LEVEL_MAP.get(str(raw_level).strip().lower(), "warning")


def _normalize_service(component: str) -> str:
    """Map an arbitrary log component name onto our known service topology when
    possible, otherwise pass it through untouched so unrecognized components
    still show up in the raw stream (just without a topology-aware service
    penalty -- they'll fall back to the "unrelated" default in distance.py).
    """
    component = str(component).strip()
    if component in ALL_SERVICES:
        return component
    lowered = component.lower()
    for svc in ALL_SERVICES:
        if svc in lowered or lowered in svc:
            return svc
    return component


def load_dataset(path: Path = None) -> list:
    """Parse a Loghub-style CSV into our alert schema. Raises DatasetLoadError
    on any problem -- missing file, missing columns, unparseable timestamps,
    or zero resulting rows.
    """
    target = Path(path) if path else (REAL_DATASET_PATH if REAL_DATASET_PATH.exists() else BUNDLED_SAMPLE)

    if not target.exists():
        raise DatasetLoadError(f"dataset file not found: {target}")

    try:
        df = pd.read_csv(target)
    except Exception as exc:
        raise DatasetLoadError(f"failed to parse CSV {target}: {exc}") from exc

    missing = REQUIRED_COLUMNS - set(c.lower() for c in df.columns)
    if missing:
        raise DatasetLoadError(f"dataset {target} missing required columns: {missing}")
    df.columns = [c.lower() for c in df.columns]

    try:
        df["ts_parsed"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    except Exception as exc:
        raise DatasetLoadError(f"failed to parse timestamps in {target}: {exc}") from exc

    if df["ts_parsed"].isna().all():
        raise DatasetLoadError(f"no parseable timestamps found in {target}")
    df = df.dropna(subset=["ts_parsed"])

    if len(df) == 0:
        raise DatasetLoadError(f"dataset {target} produced zero valid rows")

    counter = itertools.count(1)
    alerts = []
    for row in df.to_dict("records"):
        severity = _normalize_level(row["level"])
        service = _normalize_service(row["component"])
        ts = row["ts_parsed"]
        alerts.append({
            "id": f"alt-{next(counter):05d}",
            "timestamp": ts.isoformat(),
            "timestamp_unix": ts.timestamp(),
            "service": service,
            "severity": severity,
            "severity_rank": _SEVERITY_RANK[severity],
            "message": str(row["message"]),
            "source": "dataset",
            "incident_id": None,
        })

    alerts.sort(key=lambda a: a["timestamp_unix"])
    for i, a in enumerate(alerts, start=1):
        a["id"] = f"alt-{i:05d}"
    return alerts
